---
title: "Livio's Hub"
author: "Livio Finos @ DPSS, University of Padua"
date: "+39 0498276519 - livio.finos@unipd.it"
output: 
  html_document: 
    toc: yes
---

<!-- # Info -->

<!-- - <strong><a href="http://dpss.unipd.it">D.P.S.S.</a></strong>, Via Venezia, 8. Padua, Italy 35131   -->
<!-- - +39 0498276519   -->
<!-- - livio.finos@unipd.it   -->
- <a mce_real_href="/cv/finos_livio_cv.pdf" target="_blank" href="/cv/finos_livio_cv.pdf">download cv (pdf) </a>

# Research

- <a href="http://scholar.google.it/citations?hl=en&user=th0DaUwAAAAJ">@GoogleScholar</a>  
- <a href="https://www.researchgate.net/profile/Livio_Finos">@ResearchGate</a>  
- <a href="https://www.research.unipd.it/browse?type=author&authority=rp18289&sort_by=2&order=DESC&rpp=100&etal=0&submit_browse=Aggiorna#.XGHop1xKg2w">@research.unipd</a>


# Teaching

- [Teaching@UniPD](https://didattica.unipd.it/off/docente/750F8EE82FAC8ACA50EE69F79F75D23E)  
- <a href="./students/Teaching_material.html">Some teaching material</a>  
- <a href="./students/Teaching_material.html#tesi">Tesi (in italian)</a>


# Coding and Software

- [List of packages and softwares](./software/coding.html)  
- <a href="https://github.com/livioivil">more @ Github</a>

Bugs are always possible, I make my best to provide a new release averytime I found them.
Please report bugs to: 'livio.finos@unipd.it'. Peculiarities, feedback and general queries on the use and theory of the software are also welcomed.




<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-61030901-1', 'auto');
  ga('send', 'pageview');
</script>


